In [24]:
import findspark
import pandas as pd

In [2]:
findspark.init("/opt/manual/spark/")

In [3]:
from pyspark.sql import SparkSession, functions as F

# Create SparkSession

In [4]:
spark = (SparkSession.builder
        .appName("Model with Spark")
        .master("yarn")
        .enableHiveSupport()
        .getOrCreate())

# Read data

In [6]:
train_df = spark.sql("select * from homecredit.application_train_orc_snappy")

In [7]:
train_df.count()

307511

In [8]:
test_df = spark.sql("select * from homecredit.application_test_orc_snappy")

In [9]:
test_df.count()

48744

In [51]:
print(len(train_df.columns))
print(len(test_df.columns))

122
121

# Schema

In [12]:
train_df.printSchema()

root
 |-- sk_id_curr: integer (nullable = true)
 |-- target: integer (nullable = true)
 |-- name_contract_type: string (nullable = true)
 |-- code_gender: string (nullable = true)
 |-- flag_own_car: string (nullable = true)
 |-- flag_own_realty: string (nullable = true)
 |-- cnt_children: integer (nullable = true)
 |-- amt_income_total: double (nullable = true)
 |-- amt_credit: double (nullable = true)
 |-- amt_annuity: double (nullable = true)
 |-- amt_goods_price: double (nullable = true)
 |-- name_type_suite: string (nullable = true)
 |-- name_income_type: string (nullable = true)
 |-- name_education_type: string (nullable = true)
 |-- name_family_status: string (nullable = true)
 |-- name_housing_type: string (nullable = true)
 |-- region_population_relative: double (nullable = true)
 |-- days_birth: integer (nullable = true)
 |-- days_employed: integer (nullable = true)
 |-- days_registration: double (nullable = true)
 |-- days_id_publish: integer (nullable = true)
 |-- own_car_age: double (nullable = true)
 |-- flag_mobil: integer (nullable = true)
 |-- flag_emp_phone: integer (nullable = true)
 |-- flag_work_phone: integer (nullable = true)
 |-- flag_cont_mobile: integer (nullable = true)
 |-- flag_phone: integer (nullable = true)
 |-- flag_email: integer (nullable = true)
 |-- occupation_type: string (nullable = true)
 |-- cnt_fam_members: double (nullable = true)
 |-- region_rating_client: integer (nullable = true)
 |-- region_rating_client_w_city: integer (nullable = true)
 |-- weekday_appr_process_start: string (nullable = true)
 |-- hour_appr_process_start: integer (nullable = true)
 |-- reg_region_not_live_region: integer (nullable = true)
 |-- reg_region_not_work_region: integer (nullable = true)
 |-- live_region_not_work_region: integer (nullable = true)
 |-- reg_city_not_live_city: integer (nullable = true)
 |-- reg_city_not_work_city: integer (nullable = true)
 |-- live_city_not_work_city: integer (nullable = true)
 |-- organization_type: string (nullable = true)
 |-- ext_source_1: double (nullable = true)
 |-- ext_source_2: double (nullable = true)
 |-- ext_source_3: double (nullable = true)
 |-- apartments_avg: double (nullable = true)
 |-- basementarea_avg: double (nullable = true)
 |-- years_beginexpluatation_avg: double (nullable = true)
 |-- years_build_avg: double (nullable = true)
 |-- commonarea_avg: double (nullable = true)
 |-- elevators_avg: double (nullable = true)
 |-- entrances_avg: double (nullable = true)
 |-- floorsmax_avg: double (nullable = true)
 |-- floorsmin_avg: double (nullable = true)
 |-- landarea_avg: double (nullable = true)
 |-- livingapartments_avg: double (nullable = true)
 |-- livingarea_avg: double (nullable = true)
 |-- nonlivingapartments_avg: double (nullable = true)
 |-- nonlivingarea_avg: double (nullable = true)
 |-- apartments_mode: double (nullable = true)
 |-- basementarea_mode: double (nullable = true)
 |-- years_beginexpluatation_mode: double (nullable = true)
 |-- years_build_mode: double (nullable = true)
 |-- commonarea_mode: double (nullable = true)
 |-- elevators_mode: double (nullable = true)
 |-- entrances_mode: double (nullable = true)
 |-- floorsmax_mode: double (nullable = true)
 |-- floorsmin_mode: double (nullable = true)
 |-- landarea_mode: double (nullable = true)
 |-- livingapartments_mode: double (nullable = true)
 |-- livingarea_mode: double (nullable = true)
 |-- nonlivingapartments_mode: double (nullable = true)
 |-- nonlivingarea_mode: double (nullable = true)
 |-- apartments_medi: double (nullable = true)
 |-- basementarea_medi: double (nullable = true)
 |-- years_beginexpluatation_medi: double (nullable = true)
 |-- years_build_medi: double (nullable = true)
 |-- commonarea_medi: double (nullable = true)
 |-- elevators_medi: double (nullable = true)
 |-- entrances_medi: double (nullable = true)
 |-- floorsmax_medi: double (nullable = true)
 |-- floorsmin_medi: double (nullable = true)
 |-- landarea_medi: double (nullable = true)
 |-- livingapartments_medi: double (nullable = true)
 |-- livingarea_medi: double (nullable = true)
 |-- nonlivingapartments_medi: double (nullable = true)
 |-- nonlivingarea_medi: double (nullable = true)
 |-- fondkapremont_mode: string (nullable = true)
 |-- housetype_mode: string (nullable = true)
 |-- totalarea_mode: double (nullable = true)
 |-- wallsmaterial_mode: string (nullable = true)
 |-- emergencystate_mode: string (nullable = true)
 |-- obs_30_cnt_social_circle: double (nullable = true)
 |-- def_30_cnt_social_circle: double (nullable = true)
 |-- obs_60_cnt_social_circle: double (nullable = true)
 |-- def_60_cnt_social_circle: double (nullable = true)
 |-- days_last_phone_change: double (nullable = true)
 |-- flag_document_2: integer (nullable = true)
 |-- flag_document_3: integer (nullable = true)
 |-- flag_document_4: integer (nullable = true)
 |-- flag_document_5: integer (nullable = true)
 |-- flag_document_6: integer (nullable = true)
 |-- flag_document_7: integer (nullable = true)
 |-- flag_document_8: integer (nullable = true)
 |-- flag_document_9: integer (nullable = true)
 |-- flag_document_10: integer (nullable = true)
 |-- flag_document_11: integer (nullable = true)
 |-- flag_document_12: integer (nullable = true)
 |-- flag_document_13: integer (nullable = true)
 |-- flag_document_14: integer (nullable = true)
 |-- flag_document_15: integer (nullable = true)
 |-- flag_document_16: integer (nullable = true)
 |-- flag_document_17: integer (nullable = true)
 |-- flag_document_18: integer (nullable = true)
 |-- flag_document_19: integer (nullable = true)
 |-- flag_document_20: integer (nullable = true)
 |-- flag_document_21: integer (nullable = true)
 |-- amt_req_credit_bureau_hour: double (nullable = true)
 |-- amt_req_credit_bureau_day: double (nullable = true)
 |-- amt_req_credit_bureau_week: double (nullable = true)
 |-- amt_req_credit_bureau_mon: double (nullable = true)
 |-- amt_req_credit_bureau_qrt: double (nullable = true)
 |-- amt_req_credit_bureau_year: double (nullable = true)

# Null check

In [ ]:
# explore null values. Collect all in one dictionary.

In [22]:
null_dict = {
    "columns":train_df.columns,
    "null_count": [],
    "has_null":[],
    "null_ratio":[]
}
df_count = float(train_df.count())

for col in train_df.columns:
    null_count = train_df.filter( train_df[col].isNull() ).count()
    null_dict["null_count"].append(null_count)
    if  null_count > 0 :
        null_ratio = null_count/df_count
        null_dict["null_ratio"].append(null_ratio)
        null_dict["has_null"].append(True)
        print("{} has {} null and null ratio {}".format(col, null_count, round(null_ratio, 4)))
        null_columns.append(col)
    else:
        null_dict["null_ratio"].append(0.0)
        null_dict["has_null"].append(False)

amt_annuity has 12 null and null ratio 0.0
amt_goods_price has 278 null and null ratio 0.0009
own_car_age has 202929 null and null ratio 0.6599
cnt_fam_members has 2 null and null ratio 0.0
ext_source_1 has 173378 null and null ratio 0.5638
ext_source_2 has 660 null and null ratio 0.0021
ext_source_3 has 60965 null and null ratio 0.1983
apartments_avg has 156061 null and null ratio 0.5075
basementarea_avg has 179943 null and null ratio 0.5852
years_beginexpluatation_avg has 150007 null and null ratio 0.4878
years_build_avg has 204488 null and null ratio 0.665
commonarea_avg has 214865 null and null ratio 0.6987
elevators_avg has 163891 null and null ratio 0.533
entrances_avg has 154828 null and null ratio 0.5035
floorsmax_avg has 153020 null and null ratio 0.4976
floorsmin_avg has 208642 null and null ratio 0.6785
landarea_avg has 182590 null and null ratio 0.5938
livingapartments_avg has 210199 null and null ratio 0.6835
livingarea_avg has 154350 null and null ratio 0.5019
nonlivingapartments_avg has 213514 null and null ratio 0.6943
nonlivingarea_avg has 169682 null and null ratio 0.5518
apartments_mode has 156061 null and null ratio 0.5075
basementarea_mode has 179943 null and null ratio 0.5852
years_beginexpluatation_mode has 150007 null and null ratio 0.4878
years_build_mode has 204488 null and null ratio 0.665
commonarea_mode has 214865 null and null ratio 0.6987
elevators_mode has 163891 null and null ratio 0.533
entrances_mode has 154828 null and null ratio 0.5035
floorsmax_mode has 153020 null and null ratio 0.4976
floorsmin_mode has 208642 null and null ratio 0.6785
landarea_mode has 182590 null and null ratio 0.5938
livingapartments_mode has 210199 null and null ratio 0.6835
livingarea_mode has 154350 null and null ratio 0.5019
nonlivingapartments_mode has 213514 null and null ratio 0.6943
nonlivingarea_mode has 169682 null and null ratio 0.5518
apartments_medi has 156061 null and null ratio 0.5075
basementarea_medi has 179943 null and null ratio 0.5852
years_beginexpluatation_medi has 150007 null and null ratio 0.4878
years_build_medi has 204488 null and null ratio 0.665
commonarea_medi has 214865 null and null ratio 0.6987
elevators_medi has 163891 null and null ratio 0.533
entrances_medi has 154828 null and null ratio 0.5035
floorsmax_medi has 153020 null and null ratio 0.4976
floorsmin_medi has 208642 null and null ratio 0.6785
landarea_medi has 182590 null and null ratio 0.5938
livingapartments_medi has 210199 null and null ratio 0.6835
livingarea_medi has 154350 null and null ratio 0.5019
nonlivingapartments_medi has 213514 null and null ratio 0.6943
nonlivingarea_medi has 169682 null and null ratio 0.5518
totalarea_mode has 148431 null and null ratio 0.4827
obs_30_cnt_social_circle has 1021 null and null ratio 0.0033
def_30_cnt_social_circle has 1021 null and null ratio 0.0033
obs_60_cnt_social_circle has 1021 null and null ratio 0.0033
def_60_cnt_social_circle has 1021 null and null ratio 0.0033
days_last_phone_change has 1 null and null ratio 0.0
amt_req_credit_bureau_hour has 41519 null and null ratio 0.135
amt_req_credit_bureau_day has 41519 null and null ratio 0.135
amt_req_credit_bureau_week has 41519 null and null ratio 0.135
amt_req_credit_bureau_mon has 41519 null and null ratio 0.135
amt_req_credit_bureau_qrt has 41519 null and null ratio 0.135
amt_req_credit_bureau_year has 41519 null and null ratio 0.135

In [25]:
null_df = pd.DataFrame.from_dict(null_dict)

In [38]:
pd.options.display.max_rows = 999
null_df[null_df.has_null == True] \
.sort_values("null_ratio", ascending=False) \
.head(100)

                          columns  null_count  has_null  null_ratio
62                commonarea_mode      214865      True    0.698723
76                commonarea_medi      214865      True    0.698723
48                 commonarea_avg      214865      True    0.698723
70       nonlivingapartments_mode      213514      True    0.694330
56        nonlivingapartments_avg      213514      True    0.694330
84       nonlivingapartments_medi      213514      True    0.694330
82          livingapartments_medi      210199      True    0.683550
54           livingapartments_avg      210199      True    0.683550
68          livingapartments_mode      210199      True    0.683550
80                 floorsmin_medi      208642      True    0.678486
66                 floorsmin_mode      208642      True    0.678486
52                  floorsmin_avg      208642      True    0.678486
47                years_build_avg      204488      True    0.664978
61               years_build_mode      204488      True    0.664978
75               years_build_medi      204488      True    0.664978
21                    own_car_age      202929      True    0.659908
81                  landarea_medi      182590      True    0.593767
67                  landarea_mode      182590      True    0.593767
53                   landarea_avg      182590      True    0.593767
59              basementarea_mode      179943      True    0.585160
45               basementarea_avg      179943      True    0.585160
73              basementarea_medi      179943      True    0.585160
41                   ext_source_1      173378      True    0.563811
71             nonlivingarea_mode      169682      True    0.551792
57              nonlivingarea_avg      169682      True    0.551792
85             nonlivingarea_medi      169682      True    0.551792
77                 elevators_medi      163891      True    0.532960
63                 elevators_mode      163891      True    0.532960
49                  elevators_avg      163891      True    0.532960
44                 apartments_avg      156061      True    0.507497
72                apartments_medi      156061      True    0.507497
58                apartments_mode      156061      True    0.507497
50                  entrances_avg      154828      True    0.503488
78                 entrances_medi      154828      True    0.503488
64                 entrances_mode      154828      True    0.503488
83                livingarea_medi      154350      True    0.501933
55                 livingarea_avg      154350      True    0.501933
69                livingarea_mode      154350      True    0.501933
65                 floorsmax_mode      153020      True    0.497608
79                 floorsmax_medi      153020      True    0.497608
51                  floorsmax_avg      153020      True    0.497608
74   years_beginexpluatation_medi      150007      True    0.487810
46    years_beginexpluatation_avg      150007      True    0.487810
60   years_beginexpluatation_mode      150007      True    0.487810
88                 totalarea_mode      148431      True    0.482685
43                   ext_source_3       60965      True    0.198253
118    amt_req_credit_bureau_week       41519      True    0.135016
119     amt_req_credit_bureau_mon       41519      True    0.135016
116    amt_req_credit_bureau_hour       41519      True    0.135016
120     amt_req_credit_bureau_qrt       41519      True    0.135016
117     amt_req_credit_bureau_day       41519      True    0.135016
121    amt_req_credit_bureau_year       41519      True    0.135016
93       obs_60_cnt_social_circle        1021      True    0.003320
94       def_60_cnt_social_circle        1021      True    0.003320
92       def_30_cnt_social_circle        1021      True    0.003320
91       obs_30_cnt_social_circle        1021      True    0.003320
42                   ext_source_2         660      True    0.002146
10                amt_goods_price         278      True    0.000904
9                     amt_annuity          12      True    0.000039
29                cnt_fam_members           2      True    0.000007
95         days_last_phone_change           1      True    0.000003

# Drop higher ratio null columns

In [39]:
# I decide to drop columns that null rate greater than %48

In [46]:
# Select columns gt %48 null_ratio
null_df.loc[null_df.null_ratio > 0.48].loc[:,"columns"].head(100)

21                     own_car_age
41                    ext_source_1
44                  apartments_avg
45                basementarea_avg
46     years_beginexpluatation_avg
47                 years_build_avg
48                  commonarea_avg
49                   elevators_avg
50                   entrances_avg
51                   floorsmax_avg
52                   floorsmin_avg
53                    landarea_avg
54            livingapartments_avg
55                  livingarea_avg
56         nonlivingapartments_avg
57               nonlivingarea_avg
58                 apartments_mode
59               basementarea_mode
60    years_beginexpluatation_mode
61                years_build_mode
62                 commonarea_mode
63                  elevators_mode
64                  entrances_mode
65                  floorsmax_mode
66                  floorsmin_mode
67                   landarea_mode
68           livingapartments_mode
69                 livingarea_mode
70        nonlivingapartments_mode
71              nonlivingarea_mode
72                 apartments_medi
73               basementarea_medi
74    years_beginexpluatation_medi
75                years_build_medi
76                 commonarea_medi
77                  elevators_medi
78                  entrances_medi
79                  floorsmax_medi
80                  floorsmin_medi
81                   landarea_medi
82           livingapartments_medi
83                 livingarea_medi
84        nonlivingapartments_medi
85              nonlivingarea_medi
88                  totalarea_mode
Name: columns, dtype: object

In [47]:
# Convert to list columns gt %48 null_ratio
null_cols_to_drop = null_df.loc[null_df.null_ratio > 0.48].loc[:,"columns"].tolist()

In [50]:
# Drop columns gt %48 null_ratio
train_df2 = train_df.drop(*null_cols_to_drop)
test_df2 = test_df.drop(*null_cols_to_drop)

In [52]:
print(len(train_df2.columns))
print(len(test_df2.columns))

77
76

# Split numeric and categoric columns

In [69]:
categoric_cols = []
numeric_cols = []
label_col = ['target']

for col in train_df2.dtypes:
    if (col[0] not in label_col):
        if col[1] == 'string':
            categoric_cols.append(col[0])
        else:
            numeric_cols.append(col[0])

In [70]:
print(categoric_cols)

['name_contract_type', 'code_gender', 'flag_own_car', 'flag_own_realty', 'name_type_suite', 'name_income_type', 'name_education_type', 'name_family_status', 'name_housing_type', 'occupation_type', 'weekday_appr_process_start', 'organization_type', 'fondkapremont_mode', 'housetype_mode', 'wallsmaterial_mode', 'emergencystate_mode']

In [71]:
print(numeric_cols)

['sk_id_curr', 'cnt_children', 'amt_income_total', 'amt_credit', 'amt_annuity', 'amt_goods_price', 'region_population_relative', 'days_birth', 'days_employed', 'days_registration', 'days_id_publish', 'flag_mobil', 'flag_emp_phone', 'flag_work_phone', 'flag_cont_mobile', 'flag_phone', 'flag_email', 'cnt_fam_members', 'region_rating_client', 'region_rating_client_w_city', 'hour_appr_process_start', 'reg_region_not_live_region', 'reg_region_not_work_region', 'live_region_not_work_region', 'reg_city_not_live_city', 'reg_city_not_work_city', 'live_city_not_work_city', 'ext_source_2', 'ext_source_3', 'obs_30_cnt_social_circle', 'def_30_cnt_social_circle', 'obs_60_cnt_social_circle', 'def_60_cnt_social_circle', 'days_last_phone_change', 'flag_document_2', 'flag_document_3', 'flag_document_4', 'flag_document_5', 'flag_document_6', 'flag_document_7', 'flag_document_8', 'flag_document_9', 'flag_document_10', 'flag_document_11', 'flag_document_12', 'flag_document_13', 'flag_document_14', 'flag_document_15', 'flag_document_16', 'flag_document_17', 'flag_document_18', 'flag_document_19', 'flag_document_20', 'flag_document_21', 'amt_req_credit_bureau_hour', 'amt_req_credit_bureau_day', 'amt_req_credit_bureau_week', 'amt_req_credit_bureau_mon', 'amt_req_credit_bureau_qrt', 'amt_req_credit_bureau_year']

In [72]:
print(label_col)

['target']

In [73]:
print(len(categoric_cols)+len(numeric_cols)+len(label_col))

77

In [74]:
if len(train_df2.columns) == (len(categoric_cols)+len(numeric_cols)+len(label_col)):
    print("columns split is successful.")
else: print("there is a mistake column split ops.")

columns split is successful.